server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123
  #Redis相关配置
  redis:
    host: localhost
    port: 6379
    database: 0 #操作的是0号数据库
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#      logic-delete-field: isDeleted # 逻辑删除字段名
#      logic-not-delete-value: 0     # 逻辑删除字面值：未删除为0
#      logic-delete-value: 1         # 逻辑删除字面值：删除为1

#配置图片保存地址
reggie:
  path: D://img/reggie/
